services:
  nginx:
    container_name: nginx
    image: nginx:1.25.3
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/app:/var/www/html

  php:
    container_name: php
    build: ./php
    depends_on:
      - mysql
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/app:/var/www/html

  mysql:
    container_name: mysql
    image: mysql:8.2
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - TZ=Japan
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db-app:/var/lib/mysql

volumes:
  db-app: