FROM php:latest



# php_imageという名前で.階層にあるDockerfileからイメージを作る
# docker image build -t php_image .

# php_imageからphp_containnerというコンテナを作る
# docker run -it -d --name php_containner php_image

# php_containnerの中に入るコマンド
# docker exec -it php_containner bash